/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Sesion;

/**
 *
 * @author romer
 */
public class Paciente extends javax.swing.JFrame {
Sesion sesion_act;
    /**
     * Creates new form Paciente
     * @param sesion_act
     */
    public Paciente(Sesion sesion_act) {
        initComponents();
        this.sesion_act=sesion_act;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nombrestxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellidostxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        numerotxt = new javax.swing.JTextField();
        nacimientotxt = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deptxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ocupaciontxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        escolaridadtxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sexotxt = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        estadocivtxt = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        paisrestxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        deprestxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ciudadrestxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        paistxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 75, -1, -1));
        getContentPane().add(nombrestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 72, 174, -1));

        jLabel2.setText("Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 75, -1, -1));
        getContentPane().add(apellidostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 72, 178, -1));

        jLabel3.setText("Identificación: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 134, -1, -1));

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("TI");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 130, -1, -1));

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("CC");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 130, -1, -1));

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setText("CE");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 130, -1, -1));

        jLabel4.setText("Numero:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 134, -1, -1));
        getContentPane().add(numerotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 131, 180, -1));
        getContentPane().add(nacimientotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 257, 139, -1));

        jLabel5.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 263, -1, -1));

        jLabel6.setText("Pais:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 260, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 257, 98, -1));

        jLabel7.setText("Dep:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));
        getContentPane().add(deptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 257, 128, -1));

        jLabel8.setText("Ocupación: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 324, -1, -1));
        getContentPane().add(ocupaciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 324, 145, -1));

        jLabel9.setText("Escolaridad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 327, -1, -1));
        getContentPane().add(escolaridadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 324, 191, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 72, 194, -1));

        jLabel10.setText("Sexo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 199, -1, -1));

        sexotxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino", "Otros" }));
        sexotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexotxtActionPerformed(evt);
            }
        });
        getContentPane().add(sexotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 196, 110, -1));

        jLabel11.setText("Estado Civil:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 199, -1, -1));

        estadocivtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Casado/a", "Soltero/a", "Union Libre", "Viudo", "Separado" }));
        estadocivtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocivtxtActionPerformed(evt);
            }
        });
        getContentPane().add(estadocivtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 196, 103, -1));

        jLabel12.setText("Hijos:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 199, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 196, 58, -1));

        jLabel13.setText("Pais Residencia:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 396, -1, -1));
        getContentPane().add(paisrestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 393, 109, -1));

        jLabel15.setText("Departamento:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 396, -1, -1));
        getContentPane().add(deprestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 393, 99, -1));

        jLabel14.setText("Ciudad:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 396, -1, -1));
        getContentPane().add(ciudadrestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 393, 94, -1));

        jButton1.setText("Nueva Consulta");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 292, 194, -1));

        jButton5.setText("Cancelar");

        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Fotografía");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 711, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 930, -1));

        jButton3.setText("Editar datos");

        jButton4.setText("Consultar Historial");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 230, -1));

        paistxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoGen.png"))); // NOI18N
        paistxt.setText("jLabel16");
        getContentPane().add(paistxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1050, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        id_tipo = 2;
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void sexotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexotxtActionPerformed
        sextxt = sexotxt.getSelectedItem().toString();
    }//GEN-LAST:event_sexotxtActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        id_tipo = 1;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         id_tipo = 3;
                    
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void estadocivtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocivtxtActionPerformed
        estcivtxt = estadocivtxt.getSelectedItem().toString();
    }//GEN-LAST:event_estadocivtxtActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

      sesion_act.getCliente_act().setNombres(nombrestxt.getText());
      sesion_act.getCliente_act().setApellidos(apellidostxt.getText());
      sesion_act.getCliente_act().setSexo(sextxt);
      sesion_act.getCliente_act().setEstado_civil(estcivtxt);
      //cliente_act.setFecha_nac(nacimientotxt.getDate());
      sesion_act.getCliente_act().setPais(paistxtt.getText());
      sesion_act.getCliente_act().setDep(deptxt.getText());
      sesion_act.getCliente_act().setOcupacion(ocupaciontxt.getText());
      sesion_act.getCliente_act().setEscolaridad(escolaridadtxt.getText());
      sesion_act.getCliente_act().setPais_res(paisrestxt.getText());
      sesion_act.getCliente_act().setDepartamento_res(deprestxt.getText());
      sesion_act.getCliente_act().setCiudad_res(ciudadrestxt.getText());
      sesion_act.getCliente_act().setId_tipo(id_tipo);
      sesion_act.getCliente_act().setNumeroid(Integer.parseInt(numerotxt.getText()));
      sesion_act.getCliente_act().setHijos(Integer.parseInt(hijostxt.getText()));
sesion_act.getCliente_act().setIdentificacion(Integer.parseInt(numerotxt.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    String sextxt; 
    String estcivtxt;
    int id_tipo;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente(new Sesion()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidostxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ciudadrestxt;
    private javax.swing.JTextField deprestxt;
    private javax.swing.JTextField deptxt;
    private javax.swing.JTextField escolaridadtxt;
    private javax.swing.JComboBox<String> estadocivtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private com.toedter.calendar.JDateChooser nacimientotxt;
    private javax.swing.JTextField nombrestxt;
    private javax.swing.JTextField numerotxt;
    private javax.swing.JTextField ocupaciontxt;
    private javax.swing.JTextField paisrestxt;
    private javax.swing.JLabel paistxt;
    private javax.swing.JComboBox<String> sexotxt;
    // End of variables declaration//GEN-END:variables
}
